
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LCD16_2(
	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	
	
	//////////// OUTPUT //////////
	output		     [9:0]		GPIO_0 // GPIO_0[7:0] = D0-D7; GPIO_0[8] = RS; GPIO_0[9] = E
);



	
	driver_lcd u5(
		.clk(CLOCK_50),
		.pins(GPIO_0),
		.input_data(9'h141)
	);

	
	

endmodule
