
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LCD16_2(
	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 			  [3:0]			KEY,
	
	//////////// OUTPUT //////////
	output		     [9:0]		GPIO_0 // GPIO_0[7:0] = D0-D7; GPIO_0[8] = RS; GPIO_0[9] = E
);

	
	wire data_ready;
	wire lcd_busy;
	wire first_run;
	
	wire [8:0] d_in;

	wire [3:0] data_index;
	
	wire key;  // keys in positive logic
	wire key_pressed; // keys filtered by find_rise.v
	
	
	
	// keys in positive logic
	assign key  = ~KEY[0]; // keys in positive logic



	find_rise u1(
		.clk(CLOCK_50),
		.in(key),
		.out(key_pressed)
	);

	
	driver_lcd u5(
		.clk(CLOCK_50),
		.pins(GPIO_0),
		.input_data(d_in),
		.data_ready(data_ready),
		.lcd_busy(lcd_busy),
		.reset_button(key_pressed),
		.first_run(first_run)
	);
	
	controller u6(
		.clk(CLOCK_50),
		.lcd_busy(lcd_busy),
		.reset_button(key_pressed),
		.data_ready(data_ready),
		.data_index(data_index),
		.first_run(first_run)
		
	);
	
				
	memory u7(
		.index(data_index),
		.data_output(d_in)
	);
	

endmodule
